spring:
  application:
    name: ITEM-SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  zipkin:
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
server:
  servlet:
    context-path: /api

logging:
  file: /Users/mukeshkumar/development/logs/item-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}