spring:
  activemq:
    broker-url: ${ACTIVEMQ_URL:tcp://localhost:61616}
    packages:
      trust-all: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
  zipkin:
    baseUrl: ${ZIPKIN_URL:http://localhost:9411}
server:
  port: 8082
  servlet:
    context-path: /api
logging:
  file: /Users/mukeshkumar/development/logs/shipment-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}